Bikeshop/Controllers/BikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bikeshop.Extensions;
using Bikeshop.Models;
using Bikeshop.Models.Repositories.Interfaces;
using Bikeshop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bikeshop.Controllers
{
 [Authorize]
    public class BikeController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly IShoppingItemRepository _shoppingItemRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly IShoppingBagRepository _shoppingBagRepository;
        public UserManager<Customer> _userManager;


        public BikeController(IProductRepository productRepository, IShoppingItemRepository shoppingItemRepository,
            ICustomerRepository customerRepository, IShoppingBagRepository shoppingBagRepository, UserManager<Customer> userManager)
        {
            _productRepository = productRepository;
            _shoppingItemRepository = shoppingItemRepository;
            _customerRepository = customerRepository;
            _shoppingBagRepository = shoppingBagRepository;
            _userManager = userManager;
        }
        // GET
        public IActionResult Index()
        {
            var bikeViewModel = new IndexBikeViewModel()
            {
                Title = "Click on button to see details",
                Products = _productRepository.GetAllBikes().ToList(),
            };
            return View(bikeViewModel);
        }

        public IActionResult Details(int bikeId)
        {
            var bike = _productRepository.GetBikeById(bikeId);
            if (bike == null)
            {
                return NotFound();
            }

            var detailPageModel = new DetailPageModel
            {
                Product = bike,
                ShoppingItem = new ShoppingItem()
            };

            //var image = detailPageModel.Product.Image;
            return View(detailPageModel);
        }

        [HttpPost]
        public IActionResult AddToShoppingBag([FromForm]DetailPageModel model)
        {
            //Create the customer
            var userId = _userManager.GetUserId(User);
            var customer = GetCustomer(userId);

            //Get the bike
            var bike = GetProduct(model.Product.Id);

            //Create the shoppingBag if it not exists
            var shoppingBag = GetShoppingBag(customer.Id);

            var shoppingItem = _shoppingItemRepository.GetItem(model.Product.Id, shoppingBag.Id);

            if (shoppingItem == null)
            {
                shoppingItem = CreateShoppingItem(bike, model.ShoppingItem.Quantity, shoppingBag);
                _shoppingItemRepository.AddItem(shoppingItem);
            }
            else
            {
                shoppingItem.Quantity += model.ShoppingItem.Quantity;
                _shoppingItemRepository.UpdateShoppingItem(shoppingItem);
            }

            //TempData.Put("_ShoppingBag", shoppingBag);

            return RedirectToAction("Index", "ShoppingBag");
        }

        private ShoppingItem CreateShoppingItem(Product bike, int shoppingItemQuantity, ShoppingBag shoppingBag)
        {
            var shoppingItem = new ShoppingItem
            {
                Product = bike,
                Quantity = shoppingItemQuantity,
                Bag = shoppingBag
            };
            return shoppingItem;
        }

        private Customer GetCustomer(string userId)
        {
            var customer = _customerRepository.GetCustomer(userId);
            if (customer == null)
            {
                var newCustomer = new Customer
                {
                    FirstName = "Roni",
                    Name = "Size",
                    Bags = new List<ShoppingBag>()
                };
                _customerRepository.AddCustomer(newCustomer);
                customer = newCustomer;
            }
            return customer;
        }

        private Product GetProduct(int productId)
        {
            return _productRepository.GetBikeById(productId);
        }

        private ShoppingBag GetShoppingBag(string customerId)
        {
            var shoppingBag = _shoppingBagRepository.GetShoppingBag(customerId);
            if (shoppingBag == null)
            {
                var newShoppingBag = new ShoppingBag
                {
                    Customer = _customerRepository.GetCustomer(customerId),
                    Date = DateTime.Now,
                    Items = new List<ShoppingItem>()
                };
                shoppingBag = newShoppingBag;
                _shoppingBagRepository.AddItem(shoppingBag);
            }
            return shoppingBag;
        }
    }
}

Bikeshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/content/site.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" type="text/css"/>
    <title>@ViewBag.title</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Bikeshop</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Bike" asp-action="Index">Bikes</a></li>
                <li><a asp-controller="ShoppingBag" asp-action="Index">Shopping Bag</a></li>
                <partial name="_LoginPartial"/>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="banner">
    <img src="/images/banner.jpg"/>
</div>
<div class="container">
    @RenderBody()
</div>
 @RenderSection("Scripts", required: false)
<footer class="container-fluid text-center">
    <h3>The best bikes, you'll find here!</h3>
</footer>
</body>
</html>